export const Animations = {
  attention_seekers: [
    { title: 'Bounce', className: 'animate__bounce', id: 0 },
    { title: 'Flash', className: 'animate__flash', id: 1 },
    { title: 'Pulse', className: 'animate__pulse', id: 2 },
    { title: 'Rubber Band', className: 'animate__rubberBand', id: 3 },
    { title: 'ShakeX', className: 'animate__shakeX', id: 4 },
    { title: 'ShakeY', className: 'animate__shakeY', id: 5 },
    { title: 'HeadShake', className: 'animate__headShake', id: 6 },
    { title: 'Swing', className: 'animate__swing', id: 7 },
    { title: 'Tada', className: 'animate__tada', id: 8 },
    { title: 'Wobble', className: 'animate__wobble', id: 9 },
    { title: 'Jello', className: 'animate__jello', id: 10 },
    { title: 'Heart Beat', className: 'animate__heartBeat', id: 11 },
  ],
  back_entrances: [
    { title: 'BackInDown', className: 'animate__backInDown', id: 0 },
    { title: 'BackInLeft', className: 'animate__backInLeft', id: 1 },
    { title: 'BackInRight', className: 'animate__backInRight', id: 2 },
    { title: 'BackInUp', className: 'animate__backInUp', id: 3 },
  ],
  bouncing_entrances: [
    { title: 'Bounce In', className: 'animate__bounceIn', id: 0 },
    { title: 'bounceInDown', className: 'animate__bounceInDown', id: 1 },
    { title: 'bounceInLeft', className: 'animate__bounceInLeft', id: 2 },
    { title: 'bounceInRight', className: 'animate__bounceInRight', id: 3 },
    { title: 'bounceInUp', className: 'animate__bounceInUp', id: 3 },
  ],
  bouncing_exits: [
    { title: 'bounceIn', className: 'animate__bounceIn', id: 0 },
    { title: 'bounceInDown', className: 'animate__bounceInDown', id: 1 },
    { title: 'bounceInLeft', className: 'animate__bounceInLeft', id: 2 },
    { title: 'bounceInRight', className: 'animate__bounceInRight', id: 3 },
    { title: 'bounceInUp', className: 'animate__bounceInUp', id: 4 },
  ],
  fading_entrances: [
    { title: 'fadeIn', className: 'animate__fadeIn', id: 0 },
    { title: 'fadeInDown', className: 'animate__fadeInDown', id: 1 },
    { title: 'fadeInDownBig', className: 'animate__fadeInDownBig', id: 2 },
    { title: 'fadeInLeft', className: 'animate__fadeInLeft', id: 3 },
    { title: 'fadeInLeftBig', className: 'animate__fadeInLeftBig', id: 4 },
    { title: 'fadeInRight', className: 'animate__fadeInRight', id: 5 },
    { title: 'fadeInRightBig', className: 'animate__fadeInRightBig', id: 6 },
    { title: 'fadeInUp', className: 'animate__fadeInUp', id: 7 },
    { title: 'fadeInUpBig', className: 'animate__fadeInUpBig', id: 8 },
    { title: 'fadeInTopLeft', className: 'animate__fadeInTopLeft', id: 9 },
    { title: 'fadeInTopRight', className: 'animate__fadeInTopRight', id: 10 },
    {
      title: 'fadeInBottomLeft',
      className: 'animate__fadeInBottomLeft',
      id: 11,
    },
    {
      title: 'fadeInBottomRight',
      className: 'animate__fadeInBottomRight',
      id: 12,
    },
  ],
  fading_exits: [
    { title: 'fadeOut', className: 'animate__fadeOut', id: 0 },
    { title: 'fadeOutDown', className: 'animate__fadeOutDown', id: 1 },
    { title: 'fadeOutDownBig', className: 'animate__fadeOutDownBig', id: 2 },
    { title: 'fadeOutLeft', className: 'animate__fadeOutLeft', id: 3 },
    { title: 'fadeOutLeftBig', className: 'animate__fadeOutLeftBig', id: 4 },
    { title: 'fadeOutRight', className: 'animate__fadeOutRight', id: 5 },
    {
      title: 'fadeOutRightBig',
      className: 'animate__fadeOutRightBig',
      id: 6,
    },
    { title: 'fadeOutUp', className: 'animate__fadeOutUp', id: 7 },
    { title: 'fadeOutUpBig', className: 'animate__fadeOutUpBig', id: 8 },
    { title: 'fadeOutTopLeft', className: 'animate__fadeOutTopLeft', id: 9 },
    {
      title: 'fadeOutTopRight',
      className: 'animate__fadeOutTopRight',
      id: 10,
    },
    {
      title: 'fadeOutBottomRight',
      className: 'animate__fadeOutBottomRight',
      id: 11,
    },
    {
      title: 'fadeOutBottomLeft',
      className: 'animate__fadeOutBottomLeft',
      id: 12,
    },
  ],
  flippers: [
    { title: 'flip', className: 'animate__flip', id: 0 },
    { title: 'flipInX', className: 'animate__flipInX', id: 1 },
    { title: 'flipInY', className: 'animate__flipInY', id: 2 },
    { title: 'flipOutX', className: 'animate__flipOutX', id: 3 },
    { title: 'flipOutY', className: 'animate__flipOutY', id: 4 },
  ],
  light_speed: [
    {
      title: 'lightSpeedInRight',
      className: 'animate__lightSpeedInRight',
      id: 0,
    },
    {
      title: 'lightSpeedInLeft',
      className: 'animate__lightSpeedInLeft',
      id: 1,
    },
    {
      title: 'lightSpeedOutRight',
      className: 'animate__lightSpeedOutRight',
      id: 2,
    },
    {
      title: 'lightSpeedOutLeft',
      className: 'animate__lightSpeedOutLeft',
      id: 3,
    },
  ],
  rotating_entrances: [
    { title: 'rotateIn', className: 'animate__rotateIn', id: 0 },
    {
      title: 'rotateInDownLeft',
      className: 'animate__rotateInDownLeft',
      id: 1,
    },
    {
      title: 'rotateInDownRight',
      className: 'animate__rotateInDownRight',
      id: 2,
    },
    { title: 'rotateInUpLeft', className: 'animate__rotateInUpLeft', id: 3 },
    { title: 'rotateInUpRight', className: 'animate__rotateInUpRight', id: 4 },
  ],
  rotating_exits: [
    { title: 'rotateOut', className: 'animate__rotateOut', id: 0 },
    {
      title: 'rotateOutDownLeft',
      className: 'animate__rotateOutDownLeft',
      id: 1,
    },
    {
      title: 'rotateOutDownRight',
      className: 'animate__rotateOutDownRight',
      id: 2,
    },
    { title: 'rotateOutUpLeft', className: 'animate__rotateOutUpLeft', id: 3 },
    { title: 'otateOutUpRight', className: 'animate__rotateOutUpRight', id: 4 },
  ],
  specials: [
    { title: 'flip', className: 'animate__hinge', id: 0 },
    { title: 'flipInX', className: 'animate__jackInTheBox', id: 1 },
    { title: 'flipInY', className: 'animate__rollIn', id: 2 },
    { title: 'flipOutX', className: 'animate__rollOut', id: 3 },
  ],
  zooming_entrances: [
    { title: 'zoomIn', className: 'animate__zoomIn', id: 0 },
    { title: 'zoomInDown', className: 'animate__zoomInDown', id: 1 },
    { title: 'zoomInLeft', className: 'animate__zoomInLeft', id: 2 },
    { title: 'zoomInRight', className: 'animate__zoomInRight', id: 3 },
    { title: 'zoomInUp', className: 'animate__zoomInUp', id: 4 },
  ],
  zooming_exits: [
    { title: 'zoomOut', className: 'animate__zoomOut', id: 0 },
    { title: 'zoomOutDown', className: 'animate__zoomOutDown', id: 1 },
    { title: 'zoomOutLeft', className: 'animate__zoomOutLeft', id: 2 },
    { title: 'zoomOutRight', className: 'animate__zoomOutRight', id: 3 },
    { title: 'zoomOutUp', className: 'animate__zoomOutUp', id: 4 },
  ],
  sliding_entrances: [
    { title: 'slideInDown', className: 'animate__slideInDown', id: 0 },
    { title: 'slideInLeft', className: 'animate__slideInLeft', id: 1 },
    { title: 'slideInRight', className: 'animate__slideInRight', id: 2 },
    { title: 'slideInUp', className: 'animate__slideInUp', id: 3 },
  ],
  sliding_exits: [
    { title: 'slideOutDown', className: 'animate__slideOutDown', id: 0 },
    { title: 'slideOutLeft', className: 'animate__slideOutLeft', id: 1 },
    { title: 'slideOutRight', className: 'animate__slideOutRight', id: 2 },
    { title: 'slideOutUp', className: 'animate__slideOutUp', id: 3 },
  ],
};
